### ISSUE TITLE
the  ESPRI-board draws more than 1A current when it is connected with esp32

### ISSUE THREAD

**Issue by chinesejacklee** [kamilsss655/ESPRI#44]
- ordered  ESPRI-board JLCPCB
- soldered all pins manually as photos show
- plug  ESPRI-board and ESP32 together with the USB C, esp32 immediately heats up and measured 1A current draw
![IMG-3326](https://github.com/kamilsss655/ESPRI/assets/2108092/62a509b6-e165-4591-b7c0-359788fb172f)
![IMG-3325](https://github.com/kamilsss655/ESPRI/assets/2108092/a747ef38-ec3f-4172-bb7f-13ba653330fe)
![IMG-3323](https://github.com/kamilsss655/ESPRI/assets/2108092/9bbbb640-914c-4ab5-926b-16b1baadf11a)
![IMG-3324](https://github.com/kamilsss655/ESPRI/assets/2108092/6b0cbcac-fe87-4d40-afae-54d09f3df90f)

-unplug ESPRI-board, esp32 works fine draws about 50ma

**Comment by kamilsss655** [comment]
Your soldering looks good.

It looks like the polarity of all of the tantalum capacitors is wrong,
which is likely causing a short. Reference pictures on the wiki. You'll
need to reverse polarity of the tantalum capacitors (if they have not been
destroyed).

It is weird because this issue was corrected already. Did it look like this
when you ordered the board?

**Comment by chinesejacklee** [comment]
@kamilsss655 thanks! I did not check anything, just simply following the instruction on the wiki and ordered directly from JLCPCB which assembled all components for me as I am not good at soldering. I will try to resolder those capacitors and let you know how it goes.

**Comment by chinesejacklee** [comment]
resoldering capacitors solved the short overcurrent issue, but I think my esp32 board has gone due to the previous short, now it randomly reboots with or without the ESPRI-board board, from the console, I can see it says the" WDT reboots pro CPU", or something like that

**Comment by kamilsss655** [comment]
Sorry to hear. The WTD error usually means some logical issue, but maybe there is some issue with ESP as you mentioned.

It is strange since when I downloaded V1 files from `main` branch and the JLCPCB shows correct orientation:

![v1](https://github.com/kamilsss655/ESPRI/assets/8842065/07507804-eeef-4fc0-875a-cf0489d9242e)

Thus I was not able to reproduce this issue.

If you didn't edit these files you might want to raise this issue with JLCPCB.
